export const POPULAR_TICKERS = [
  { ticker: 'AAPL', name: '애플' },
  { ticker: 'MSFT', name: '마이크로소프트' },
  { ticker: 'GOOGL', name: '알파벳 (구글)' },
  { ticker: 'AMZN', name: '아마존' },
  { ticker: 'NVDA', name: '엔비디아' },
  { ticker: 'TSLA', name: '테슬라' },
  { ticker: 'META', name: '메타' },
  { ticker: 'BRK.B', name: '버크셔 해서웨이' },
  { ticker: 'JPM', name: 'JP모건' },
  { ticker: 'V', name: '비자' },
  { ticker: 'JNJ', name: '존슨앤존슨' },
  { ticker: 'WMT', name: '월마트' },
  { ticker: 'MA', name: '마스터카드' },
  { ticker: 'PG', name: 'P&G' },
  { ticker: 'HD', name: '홈디포' },
  { ticker: 'XOM', name: '엑손모빌' },
  { ticker: 'BAC', name: '뱅크오브아메리카' },
  { ticker: 'KO', name: '코카콜라' },
  { ticker: 'PEP', name: '펩시코' },
  { ticker: 'COST', name: '코스트코' },
  { ticker: 'ABBV', name: '애브비' },
  { ticker: 'MRK', name: '머크' },
  { ticker: 'AVGO', name: '브로드컴' },
  { ticker: 'CVX', name: '셰브론' },
  { ticker: 'LLY', name: '일라이릴리' },
  { ticker: 'AMD', name: 'AMD' },
  { ticker: 'ADBE', name: '어도비' },
  { ticker: 'CRM', name: '세일즈포스' },
  { ticker: 'NFLX', name: '넷플릭스' },
  { ticker: 'DIS', name: '디즈니' },
  { ticker: 'INTC', name: '인텔' },
  { ticker: 'CSCO', name: '시스코' },
  { ticker: 'CMCSA', name: '컴캐스트' },
  { ticker: 'VZ', name: '버라이즌' },
  { ticker: 'NKE', name: '나이키' },
  { ticker: 'PYPL', name: '페이팔' },
  { ticker: 'QCOM', name: '퀄컴' },
  { ticker: 'T', name: 'AT&T' },
  { ticker: 'UNH', name: '유나이티드헬스' },
  { ticker: 'MCD', name: '맥도날드' },
  { ticker: 'ORCL', name: '오라클' },
  { ticker: 'UBER', name: '우버' },
  { ticker: 'SQ', name: '블록 (스퀘어)' },
  { ticker: 'SNAP', name: '스냅' },
  { ticker: 'PLTR', name: '팔란티어' },
  { ticker: 'COIN', name: '코인베이스' },
  { ticker: 'RIVN', name: '리비안' },
  { ticker: 'SOFI', name: '소파이' },
  { ticker: 'SPY', name: 'S&P 500 ETF' },
  { ticker: 'QQQ', name: '나스닥 100 ETF' },
] as const
