-- Stock seed data
-- Using MERGE INTO for H2 compatibility (dev), MySQL uses spring.sql.init.mode=never in prod
MERGE INTO stocks (ticker, name_en, name_ko, logo_url) KEY(ticker) VALUES
('AAPL', 'Apple Inc.', '애플', 'https://cdn.tickerlogos.com/apple.com'),
('MSFT', 'Microsoft Corporation', '마이크로소프트', 'https://cdn.tickerlogos.com/microsoft.com'),
('GOOGL', 'Alphabet Inc.', '알파벳 (구글)', 'https://cdn.tickerlogos.com/google.com'),
('AMZN', 'Amazon.com Inc.', '아마존', 'https://cdn.tickerlogos.com/amazon.com'),
('NVDA', 'NVIDIA Corporation', '엔비디아', 'https://cdn.tickerlogos.com/nvidia.com'),
('TSLA', 'Tesla Inc.', '테슬라', 'https://cdn.tickerlogos.com/tesla.com'),
('META', 'Meta Platforms Inc.', '메타', 'https://cdn.tickerlogos.com/meta.com'),
('BRK.B', 'Berkshire Hathaway Inc.', '버크셔 해서웨이', 'https://cdn.tickerlogos.com/berkshirehathaway.com'),
('JPM', 'JPMorgan Chase & Co.', 'JP모건', 'https://cdn.tickerlogos.com/jpmorganchase.com'),
('V', 'Visa Inc.', '비자', 'https://cdn.tickerlogos.com/visa.com'),
('JNJ', 'Johnson & Johnson', '존슨앤존슨', 'https://cdn.tickerlogos.com/jnj.com'),
('WMT', 'Walmart Inc.', '월마트', 'https://cdn.tickerlogos.com/walmart.com'),
('MA', 'Mastercard Inc.', '마스터카드', 'https://cdn.tickerlogos.com/mastercard.com'),
('PG', 'Procter & Gamble Co.', 'P&G', 'https://cdn.tickerlogos.com/pg.com'),
('HD', 'The Home Depot Inc.', '홈디포', 'https://cdn.tickerlogos.com/homedepot.com'),
('XOM', 'Exxon Mobil Corporation', '엑손모빌', 'https://cdn.tickerlogos.com/exxonmobil.com'),
('BAC', 'Bank of America Corp.', '뱅크오브아메리카', 'https://cdn.tickerlogos.com/bankofamerica.com'),
('KO', 'The Coca-Cola Company', '코카콜라', 'https://cdn.tickerlogos.com/coca-cola.com'),
('PEP', 'PepsiCo Inc.', '펩시코', 'https://cdn.tickerlogos.com/pepsico.com'),
('COST', 'Costco Wholesale Corp.', '코스트코', 'https://cdn.tickerlogos.com/costco.com'),
('ABBV', 'AbbVie Inc.', '애브비', 'https://cdn.tickerlogos.com/abbvie.com'),
('MRK', 'Merck & Co. Inc.', '머크', 'https://cdn.tickerlogos.com/merck.com'),
('AVGO', 'Broadcom Inc.', '브로드컴', 'https://cdn.tickerlogos.com/broadcom.com'),
('CVX', 'Chevron Corporation', '셰브론', 'https://cdn.tickerlogos.com/chevron.com'),
('LLY', 'Eli Lilly and Company', '일라이릴리', 'https://cdn.tickerlogos.com/lilly.com'),
('AMD', 'Advanced Micro Devices', 'AMD', 'https://cdn.tickerlogos.com/amd.com'),
('ADBE', 'Adobe Inc.', '어도비', 'https://cdn.tickerlogos.com/adobe.com'),
('CRM', 'Salesforce Inc.', '세일즈포스', 'https://cdn.tickerlogos.com/salesforce.com'),
('NFLX', 'Netflix Inc.', '넷플릭스', 'https://cdn.tickerlogos.com/netflix.com'),
('DIS', 'The Walt Disney Company', '디즈니', 'https://cdn.tickerlogos.com/disney.com'),
('INTC', 'Intel Corporation', '인텔', 'https://cdn.tickerlogos.com/intel.com'),
('CSCO', 'Cisco Systems Inc.', '시스코', 'https://cdn.tickerlogos.com/cisco.com'),
('CMCSA', 'Comcast Corporation', '컴캐스트', 'https://cdn.tickerlogos.com/comcast.com'),
('VZ', 'Verizon Communications', '버라이즌', 'https://cdn.tickerlogos.com/verizon.com'),
('NKE', 'Nike Inc.', '나이키', 'https://cdn.tickerlogos.com/nike.com'),
('PYPL', 'PayPal Holdings Inc.', '페이팔', 'https://cdn.tickerlogos.com/paypal.com'),
('QCOM', 'Qualcomm Inc.', '퀄컴', 'https://cdn.tickerlogos.com/qualcomm.com'),
('T', 'AT&T Inc.', 'AT&T', 'https://cdn.tickerlogos.com/att.com'),
('UNH', 'UnitedHealth Group', '유나이티드헬스', 'https://cdn.tickerlogos.com/unitedhealthgroup.com'),
('MCD', 'McDonald''s Corporation', '맥도날드', 'https://cdn.tickerlogos.com/mcdonalds.com'),
('ORCL', 'Oracle Corporation', '오라클', 'https://cdn.tickerlogos.com/oracle.com'),
('UBER', 'Uber Technologies Inc.', '우버', 'https://cdn.tickerlogos.com/uber.com'),
('SQ', 'Block Inc.', '블록 (스퀘어)', 'https://cdn.tickerlogos.com/block.xyz'),
('SNAP', 'Snap Inc.', '스냅', 'https://cdn.tickerlogos.com/snap.com'),
('PLTR', 'Palantir Technologies', '팔란티어', 'https://cdn.tickerlogos.com/palantir.com'),
('COIN', 'Coinbase Global Inc.', '코인베이스', 'https://cdn.tickerlogos.com/coinbase.com'),
('RIVN', 'Rivian Automotive Inc.', '리비안', 'https://cdn.tickerlogos.com/rivian.com'),
('SOFI', 'SoFi Technologies Inc.', '소파이', 'https://cdn.tickerlogos.com/sofi.com'),
('SPY', 'SPDR S&P 500 ETF Trust', 'S&P 500 ETF', NULL),
('QQQ', 'Invesco QQQ Trust', '나스닥 100 ETF', NULL),
-- Additional popular stocks
('GOOG', 'Alphabet Inc. Class C', '알파벳 C', 'https://cdn.tickerlogos.com/google.com'),
('BRK.A', 'Berkshire Hathaway Class A', '버크셔 해서웨이 A', 'https://cdn.tickerlogos.com/berkshirehathaway.com'),
('TMO', 'Thermo Fisher Scientific', '써모피셔', 'https://cdn.tickerlogos.com/thermofisher.com'),
('ABT', 'Abbott Laboratories', '애보트', 'https://cdn.tickerlogos.com/abbott.com'),
('DHR', 'Danaher Corporation', '다나허', 'https://cdn.tickerlogos.com/danaher.com'),
('PFE', 'Pfizer Inc.', '화이자', 'https://cdn.tickerlogos.com/pfizer.com'),
('TXN', 'Texas Instruments', '텍사스인스트루먼트', 'https://cdn.tickerlogos.com/ti.com'),
('PM', 'Philip Morris International', '필립모리스', 'https://cdn.tickerlogos.com/pmi.com'),
('RTX', 'RTX Corporation', 'RTX', 'https://cdn.tickerlogos.com/rtx.com'),
('SPGI', 'S&P Global Inc.', 'S&P글로벌', 'https://cdn.tickerlogos.com/spglobal.com'),
('NEE', 'NextEra Energy Inc.', '넥스트에라에너지', 'https://cdn.tickerlogos.com/nexteraenergy.com'),
('HON', 'Honeywell International', '허니웰', 'https://cdn.tickerlogos.com/honeywell.com'),
('UNP', 'Union Pacific Corp.', '유니언퍼시픽', 'https://cdn.tickerlogos.com/up.com'),
('LOW', 'Lowe''s Companies Inc.', '로우스', 'https://cdn.tickerlogos.com/lowes.com'),
('IBM', 'International Business Machines', 'IBM', 'https://cdn.tickerlogos.com/ibm.com'),
('GS', 'Goldman Sachs Group', '골드만삭스', 'https://cdn.tickerlogos.com/goldmansachs.com'),
('MS', 'Morgan Stanley', '모건스탠리', 'https://cdn.tickerlogos.com/morganstanley.com'),
('BLK', 'BlackRock Inc.', '블랙록', 'https://cdn.tickerlogos.com/blackrock.com'),
('CAT', 'Caterpillar Inc.', '캐터필러', 'https://cdn.tickerlogos.com/caterpillar.com'),
('DE', 'Deere & Company', '디어', 'https://cdn.tickerlogos.com/deere.com'),
('AMAT', 'Applied Materials Inc.', '어플라이드머티리얼즈', 'https://cdn.tickerlogos.com/appliedmaterials.com'),
('LRCX', 'Lam Research Corp.', '램리서치', 'https://cdn.tickerlogos.com/lamresearch.com'),
('NOW', 'ServiceNow Inc.', '서비스나우', 'https://cdn.tickerlogos.com/servicenow.com'),
('ISRG', 'Intuitive Surgical Inc.', '인튜이티브서지컬', 'https://cdn.tickerlogos.com/intuitive.com'),
('BKNG', 'Booking Holdings Inc.', '부킹홀딩스', 'https://cdn.tickerlogos.com/booking.com'),
('AXP', 'American Express Co.', '아메리칸익스프레스', 'https://cdn.tickerlogos.com/americanexpress.com'),
('SBUX', 'Starbucks Corporation', '스타벅스', 'https://cdn.tickerlogos.com/starbucks.com'),
('MDLZ', 'Mondelez International', '몬델리즈', 'https://cdn.tickerlogos.com/mondelezinternational.com'),
('GE', 'GE Aerospace', 'GE에어로스페이스', 'https://cdn.tickerlogos.com/geaerospace.com'),
('MMM', '3M Company', '3M', 'https://cdn.tickerlogos.com/3m.com'),
('BA', 'The Boeing Company', '보잉', 'https://cdn.tickerlogos.com/boeing.com'),
('LMT', 'Lockheed Martin Corp.', '록히드마틴', 'https://cdn.tickerlogos.com/lockheedmartin.com'),
('SHOP', 'Shopify Inc.', '쇼피파이', 'https://cdn.tickerlogos.com/shopify.com'),
('MRVL', 'Marvell Technology', '마벨테크놀로지', 'https://cdn.tickerlogos.com/marvell.com'),
('MU', 'Micron Technology', '마이크론', 'https://cdn.tickerlogos.com/micron.com'),
('PANW', 'Palo Alto Networks', '팔로알토네트웍스', 'https://cdn.tickerlogos.com/paloaltonetworks.com'),
('CRWD', 'CrowdStrike Holdings', '크라우드스트라이크', 'https://cdn.tickerlogos.com/crowdstrike.com'),
('ABNB', 'Airbnb Inc.', '에어비앤비', 'https://cdn.tickerlogos.com/airbnb.com'),
('ARM', 'Arm Holdings plc', 'ARM', 'https://cdn.tickerlogos.com/arm.com'),
('SNOW', 'Snowflake Inc.', '스노우플레이크', 'https://cdn.tickerlogos.com/snowflake.com'),
('NET', 'Cloudflare Inc.', '클라우드플레어', 'https://cdn.tickerlogos.com/cloudflare.com'),
('DDOG', 'Datadog Inc.', '데이터독', 'https://cdn.tickerlogos.com/datadoghq.com'),
('ZS', 'Zscaler Inc.', '지스케일러', 'https://cdn.tickerlogos.com/zscaler.com'),
('FTNT', 'Fortinet Inc.', '포티넷', 'https://cdn.tickerlogos.com/fortinet.com'),
('ENPH', 'Enphase Energy Inc.', '엔페이즈에너지', 'https://cdn.tickerlogos.com/enphase.com'),
('SEDG', 'SolarEdge Technologies', '솔라엣지', 'https://cdn.tickerlogos.com/solaredge.com'),
('VOO', 'Vanguard S&P 500 ETF', 'S&P 500 ETF (뱅가드)', NULL),
('IVV', 'iShares Core S&P 500 ETF', 'S&P 500 ETF (아이셰어즈)', NULL),
('VTI', 'Vanguard Total Stock Market ETF', '미국 전체주식 ETF', NULL),
('ARKK', 'ARK Innovation ETF', 'ARK 이노베이션 ETF', NULL),
('SOXX', 'iShares Semiconductor ETF', '반도체 ETF', NULL),
('XLF', 'Financial Select Sector SPDR', '금융 섹터 ETF', NULL),
('XLE', 'Energy Select Sector SPDR', '에너지 섹터 ETF', NULL);
