-- Stock seed data
-- Using INSERT IGNORE for MySQL compatibility
INSERT IGNORE INTO stocks (ticker, name_en, name_ko, logo_url, sector, exchange, active) VALUES
('AAPL', 'Apple Inc.', '애플', 'https://cdn.tickerlogos.com/apple.com', 'Technology', 'NASDAQ', true),
('MSFT', 'Microsoft Corporation', '마이크로소프트', 'https://cdn.tickerlogos.com/microsoft.com', 'Technology', 'NASDAQ', true),
('GOOGL', 'Alphabet Inc.', '알파벳 (구글)', 'https://cdn.tickerlogos.com/google.com', 'Technology', 'NASDAQ', true),
('AMZN', 'Amazon.com Inc.', '아마존', 'https://cdn.tickerlogos.com/amazon.com', 'Consumer Cyclical', 'NASDAQ', true),
('NVDA', 'NVIDIA Corporation', '엔비디아', 'https://cdn.tickerlogos.com/nvidia.com', 'Technology', 'NASDAQ', true),
('TSLA', 'Tesla Inc.', '테슬라', 'https://cdn.tickerlogos.com/tesla.com', 'Consumer Cyclical', 'NASDAQ', true),
('META', 'Meta Platforms Inc.', '메타', 'https://cdn.tickerlogos.com/meta.com', 'Technology', 'NASDAQ', true),
('BRK.B', 'Berkshire Hathaway Inc.', '버크셔 해서웨이', 'https://cdn.tickerlogos.com/berkshirehathaway.com', 'Financial Services', 'NYSE', true),
('JPM', 'JPMorgan Chase & Co.', 'JP모건', 'https://cdn.tickerlogos.com/jpmorganchase.com', 'Financial Services', 'NYSE', true),
('V', 'Visa Inc.', '비자', 'https://cdn.tickerlogos.com/visa.com', 'Financial Services', 'NYSE', true),
('JNJ', 'Johnson & Johnson', '존슨앤존슨', 'https://cdn.tickerlogos.com/jnj.com', 'Healthcare', 'NYSE', true),
('WMT', 'Walmart Inc.', '월마트', 'https://cdn.tickerlogos.com/walmart.com', 'Consumer Defensive', 'NYSE', true),
('MA', 'Mastercard Inc.', '마스터카드', 'https://cdn.tickerlogos.com/mastercard.com', 'Financial Services', 'NYSE', true),
('PG', 'Procter & Gamble Co.', 'P&G', 'https://cdn.tickerlogos.com/pg.com', 'Consumer Defensive', 'NYSE', true),
('HD', 'The Home Depot Inc.', '홈디포', 'https://cdn.tickerlogos.com/homedepot.com', 'Consumer Cyclical', 'NYSE', true),
('XOM', 'Exxon Mobil Corporation', '엑손모빌', 'https://cdn.tickerlogos.com/exxonmobil.com', 'Energy', 'NYSE', true),
('BAC', 'Bank of America Corp.', '뱅크오브아메리카', 'https://cdn.tickerlogos.com/bankofamerica.com', 'Financial Services', 'NYSE', true),
('KO', 'The Coca-Cola Company', '코카콜라', 'https://cdn.tickerlogos.com/coca-cola.com', 'Consumer Defensive', 'NYSE', true),
('PEP', 'PepsiCo Inc.', '펩시코', 'https://cdn.tickerlogos.com/pepsico.com', 'Consumer Defensive', 'NASDAQ', true),
('COST', 'Costco Wholesale Corp.', '코스트코', 'https://cdn.tickerlogos.com/costco.com', 'Consumer Defensive', 'NASDAQ', true),
('ABBV', 'AbbVie Inc.', '애브비', 'https://cdn.tickerlogos.com/abbvie.com', 'Healthcare', 'NYSE', true),
('MRK', 'Merck & Co. Inc.', '머크', 'https://cdn.tickerlogos.com/merck.com', 'Healthcare', 'NYSE', true),
('AVGO', 'Broadcom Inc.', '브로드컴', 'https://cdn.tickerlogos.com/broadcom.com', 'Technology', 'NASDAQ', true),
('CVX', 'Chevron Corporation', '셰브론', 'https://cdn.tickerlogos.com/chevron.com', 'Energy', 'NYSE', true),
('LLY', 'Eli Lilly and Company', '일라이릴리', 'https://cdn.tickerlogos.com/lilly.com', 'Healthcare', 'NYSE', true),
('AMD', 'Advanced Micro Devices', 'AMD', 'https://cdn.tickerlogos.com/amd.com', 'Technology', 'NASDAQ', true),
('ADBE', 'Adobe Inc.', '어도비', 'https://cdn.tickerlogos.com/adobe.com', 'Technology', 'NASDAQ', true),
('CRM', 'Salesforce Inc.', '세일즈포스', 'https://cdn.tickerlogos.com/salesforce.com', 'Technology', 'NYSE', true),
('NFLX', 'Netflix Inc.', '넷플릭스', 'https://cdn.tickerlogos.com/netflix.com', 'Communication Services', 'NASDAQ', true),
('DIS', 'The Walt Disney Company', '디즈니', 'https://cdn.tickerlogos.com/disney.com', 'Communication Services', 'NYSE', true),
('INTC', 'Intel Corporation', '인텔', 'https://cdn.tickerlogos.com/intel.com', 'Technology', 'NASDAQ', true),
('CSCO', 'Cisco Systems Inc.', '시스코', 'https://cdn.tickerlogos.com/cisco.com', 'Technology', 'NASDAQ', true),
('CMCSA', 'Comcast Corporation', '컴캐스트', 'https://cdn.tickerlogos.com/comcast.com', 'Communication Services', 'NASDAQ', true),
('VZ', 'Verizon Communications', '버라이즌', 'https://cdn.tickerlogos.com/verizon.com', 'Communication Services', 'NYSE', true),
('NKE', 'Nike Inc.', '나이키', 'https://cdn.tickerlogos.com/nike.com', 'Consumer Cyclical', 'NYSE', true),
('PYPL', 'PayPal Holdings Inc.', '페이팔', 'https://cdn.tickerlogos.com/paypal.com', 'Financial Services', 'NASDAQ', true),
('QCOM', 'Qualcomm Inc.', '퀄컴', 'https://cdn.tickerlogos.com/qualcomm.com', 'Technology', 'NASDAQ', true),
('T', 'AT&T Inc.', 'AT&T', 'https://cdn.tickerlogos.com/att.com', 'Communication Services', 'NYSE', true),
('UNH', 'UnitedHealth Group', '유나이티드헬스', 'https://cdn.tickerlogos.com/unitedhealthgroup.com', 'Healthcare', 'NYSE', true),
('MCD', 'McDonald''s Corporation', '맥도날드', 'https://cdn.tickerlogos.com/mcdonalds.com', 'Consumer Cyclical', 'NYSE', true),
('ORCL', 'Oracle Corporation', '오라클', 'https://cdn.tickerlogos.com/oracle.com', 'Technology', 'NYSE', true),
('UBER', 'Uber Technologies Inc.', '우버', 'https://cdn.tickerlogos.com/uber.com', 'Technology', 'NYSE', true),
('SQ', 'Block Inc.', '블록 (스퀘어)', 'https://cdn.tickerlogos.com/block.xyz', 'Technology', 'NYSE', true),
('SNAP', 'Snap Inc.', '스냅', 'https://cdn.tickerlogos.com/snap.com', 'Communication Services', 'NYSE', true),
('PLTR', 'Palantir Technologies', '팔란티어', 'https://cdn.tickerlogos.com/palantir.com', 'Technology', 'NASDAQ', true),
('COIN', 'Coinbase Global Inc.', '코인베이스', 'https://cdn.tickerlogos.com/coinbase.com', 'Financial Services', 'NASDAQ', true),
('RIVN', 'Rivian Automotive Inc.', '리비안', 'https://cdn.tickerlogos.com/rivian.com', 'Consumer Cyclical', 'NASDAQ', true),
('SOFI', 'SoFi Technologies Inc.', '소파이', 'https://cdn.tickerlogos.com/sofi.com', 'Financial Services', 'NASDAQ', true),
('SPY', 'SPDR S&P 500 ETF Trust', 'S&P 500 ETF', NULL, 'ETF', 'NYSE', true),
('QQQ', 'Invesco QQQ Trust', '나스닥 100 ETF', NULL, 'ETF', 'NASDAQ', true),
-- Additional popular stocks
('GOOG', 'Alphabet Inc. Class C', '알파벳 C', 'https://cdn.tickerlogos.com/google.com', 'Technology', 'NASDAQ', true),
('BRK.A', 'Berkshire Hathaway Class A', '버크셔 해서웨이 A', 'https://cdn.tickerlogos.com/berkshirehathaway.com', 'Financial Services', 'NYSE', true),
('TMO', 'Thermo Fisher Scientific', '써모피셔', 'https://cdn.tickerlogos.com/thermofisher.com', 'Healthcare', 'NYSE', true),
('ABT', 'Abbott Laboratories', '애보트', 'https://cdn.tickerlogos.com/abbott.com', 'Healthcare', 'NYSE', true),
('DHR', 'Danaher Corporation', '다나허', 'https://cdn.tickerlogos.com/danaher.com', 'Healthcare', 'NYSE', true),
('PFE', 'Pfizer Inc.', '화이자', 'https://cdn.tickerlogos.com/pfizer.com', 'Healthcare', 'NYSE', true),
('TXN', 'Texas Instruments', '텍사스인스트루먼트', 'https://cdn.tickerlogos.com/ti.com', 'Technology', 'NASDAQ', true),
('PM', 'Philip Morris International', '필립모리스', 'https://cdn.tickerlogos.com/pmi.com', 'Consumer Defensive', 'NYSE', true),
('RTX', 'RTX Corporation', 'RTX', 'https://cdn.tickerlogos.com/rtx.com', 'Industrials', 'NYSE', true),
('SPGI', 'S&P Global Inc.', 'S&P글로벌', 'https://cdn.tickerlogos.com/spglobal.com', 'Financial Services', 'NYSE', true),
('NEE', 'NextEra Energy Inc.', '넥스트에라에너지', 'https://cdn.tickerlogos.com/nexteraenergy.com', 'Utilities', 'NYSE', true),
('HON', 'Honeywell International', '허니웰', 'https://cdn.tickerlogos.com/honeywell.com', 'Industrials', 'NASDAQ', true),
('UNP', 'Union Pacific Corp.', '유니언퍼시픽', 'https://cdn.tickerlogos.com/up.com', 'Industrials', 'NYSE', true),
('LOW', 'Lowe''s Companies Inc.', '로우스', 'https://cdn.tickerlogos.com/lowes.com', 'Consumer Cyclical', 'NYSE', true),
('IBM', 'International Business Machines', 'IBM', 'https://cdn.tickerlogos.com/ibm.com', 'Technology', 'NYSE', true),
('GS', 'Goldman Sachs Group', '골드만삭스', 'https://cdn.tickerlogos.com/goldmansachs.com', 'Financial Services', 'NYSE', true),
('MS', 'Morgan Stanley', '모건스탠리', 'https://cdn.tickerlogos.com/morganstanley.com', 'Financial Services', 'NYSE', true),
('BLK', 'BlackRock Inc.', '블랙록', 'https://cdn.tickerlogos.com/blackrock.com', 'Financial Services', 'NYSE', true),
('CAT', 'Caterpillar Inc.', '캐터필러', 'https://cdn.tickerlogos.com/caterpillar.com', 'Industrials', 'NYSE', true),
('DE', 'Deere & Company', '디어', 'https://cdn.tickerlogos.com/deere.com', 'Industrials', 'NYSE', true),
('AMAT', 'Applied Materials Inc.', '어플라이드머티리얼즈', 'https://cdn.tickerlogos.com/appliedmaterials.com', 'Technology', 'NASDAQ', true),
('LRCX', 'Lam Research Corp.', '램리서치', 'https://cdn.tickerlogos.com/lamresearch.com', 'Technology', 'NASDAQ', true),
('NOW', 'ServiceNow Inc.', '서비스나우', 'https://cdn.tickerlogos.com/servicenow.com', 'Technology', 'NYSE', true),
('ISRG', 'Intuitive Surgical Inc.', '인튜이티브서지컬', 'https://cdn.tickerlogos.com/intuitive.com', 'Healthcare', 'NASDAQ', true),
('BKNG', 'Booking Holdings Inc.', '부킹홀딩스', 'https://cdn.tickerlogos.com/booking.com', 'Consumer Cyclical', 'NASDAQ', true),
('AXP', 'American Express Co.', '아메리칸익스프레스', 'https://cdn.tickerlogos.com/americanexpress.com', 'Financial Services', 'NYSE', true),
('SBUX', 'Starbucks Corporation', '스타벅스', 'https://cdn.tickerlogos.com/starbucks.com', 'Consumer Cyclical', 'NASDAQ', true),
('MDLZ', 'Mondelez International', '몬델리즈', 'https://cdn.tickerlogos.com/mondelezinternational.com', 'Consumer Defensive', 'NASDAQ', true),
('GE', 'GE Aerospace', 'GE에어로스페이스', 'https://cdn.tickerlogos.com/geaerospace.com', 'Industrials', 'NYSE', true),
('MMM', '3M Company', '3M', 'https://cdn.tickerlogos.com/3m.com', 'Industrials', 'NYSE', true),
('BA', 'The Boeing Company', '보잉', 'https://cdn.tickerlogos.com/boeing.com', 'Industrials', 'NYSE', true),
('LMT', 'Lockheed Martin Corp.', '록히드마틴', 'https://cdn.tickerlogos.com/lockheedmartin.com', 'Industrials', 'NYSE', true),
('SHOP', 'Shopify Inc.', '쇼피파이', 'https://cdn.tickerlogos.com/shopify.com', 'Technology', 'NYSE', true),
('MRVL', 'Marvell Technology', '마벨테크놀로지', 'https://cdn.tickerlogos.com/marvell.com', 'Technology', 'NASDAQ', true),
('MU', 'Micron Technology', '마이크론', 'https://cdn.tickerlogos.com/micron.com', 'Technology', 'NASDAQ', true),
('PANW', 'Palo Alto Networks', '팔로알토네트웍스', 'https://cdn.tickerlogos.com/paloaltonetworks.com', 'Technology', 'NASDAQ', true),
('CRWD', 'CrowdStrike Holdings', '크라우드스트라이크', 'https://cdn.tickerlogos.com/crowdstrike.com', 'Technology', 'NASDAQ', true),
('ABNB', 'Airbnb Inc.', '에어비앤비', 'https://cdn.tickerlogos.com/airbnb.com', 'Consumer Cyclical', 'NASDAQ', true),
('ARM', 'Arm Holdings plc', 'ARM', 'https://cdn.tickerlogos.com/arm.com', 'Technology', 'NASDAQ', true),
('SNOW', 'Snowflake Inc.', '스노우플레이크', 'https://cdn.tickerlogos.com/snowflake.com', 'Technology', 'NYSE', true),
('NET', 'Cloudflare Inc.', '클라우드플레어', 'https://cdn.tickerlogos.com/cloudflare.com', 'Technology', 'NYSE', true),
('DDOG', 'Datadog Inc.', '데이터독', 'https://cdn.tickerlogos.com/datadoghq.com', 'Technology', 'NASDAQ', true),
('ZS', 'Zscaler Inc.', '지스케일러', 'https://cdn.tickerlogos.com/zscaler.com', 'Technology', 'NASDAQ', true),
('FTNT', 'Fortinet Inc.', '포티넷', 'https://cdn.tickerlogos.com/fortinet.com', 'Technology', 'NASDAQ', true),
('ENPH', 'Enphase Energy Inc.', '엔페이즈에너지', 'https://cdn.tickerlogos.com/enphase.com', 'Technology', 'NASDAQ', true),
('SEDG', 'SolarEdge Technologies', '솔라엣지', 'https://cdn.tickerlogos.com/solaredge.com', 'Technology', 'NASDAQ', true),
('VOO', 'Vanguard S&P 500 ETF', 'S&P 500 ETF (뱅가드)', NULL, 'ETF', 'NYSE', true),
('IVV', 'iShares Core S&P 500 ETF', 'S&P 500 ETF (아이셰어즈)', NULL, 'ETF', 'NYSE', true),
('VTI', 'Vanguard Total Stock Market ETF', '미국 전체주식 ETF', NULL, 'ETF', 'NYSE', true),
('ARKK', 'ARK Innovation ETF', 'ARK 이노베이션 ETF', NULL, 'ETF', 'NYSE', true),
('SOXX', 'iShares Semiconductor ETF', '반도체 ETF', NULL, 'ETF', 'NASDAQ', true),
('XLF', 'Financial Select Sector SPDR', '금융 섹터 ETF', NULL, 'ETF', 'NYSE', true),
('XLE', 'Energy Select Sector SPDR', '에너지 섹터 ETF', NULL, 'ETF', 'NYSE', true);

-- Fix trade_images.data column type for large image uploads
ALTER TABLE trade_images MODIFY COLUMN data LONGBLOB NOT NULL;
